version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: g_scores_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: g_scores
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: ../../
      dockerfile: apps/backend/Dockerfile
      target: builder
    container_name: g_scores_backend
    command: npm run dev
    volumes:
      - ../../apps/backend/src:/app/apps/backend/src
      - ../../apps/backend/.env.development:/app/apps/backend/.env.development
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/g_scores?schema=public
    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    build:
      context: ../../
      dockerfile: apps/frontend/Dockerfile
      target: builder
    container_name: g_scores_frontend
    command: npm run dev -- --host
    volumes:
      - ../../apps/frontend/src:/app/apps/frontend/src
      - ../../apps/frontend/.env.development:/app/apps/frontend/.env.development
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000/api/v1
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  pgdata:
