version: '3.8'

services:
  backend:
    build:
      target: runner
    command: npm run start:prod
    volumes: []

  frontend:
    build:
      target: runner
      args:
        - VITE_API_URL=http://localhost:3000/api/v1
    command: nginx -g "daemon off;"
    ports:
      - "80:80"
    volumes: []
